core/urls.py
from django import views
from django.urls import path, include
from core.views import create_checkout_session, save_checkout_info, add_to_cart, add_to_wishlist, ajax_add_review, ajax_contact_form, cart_view, category_list_view, category_product_list__view, checkout, customer_dashboard, delete_item_from_cart, filter_product, index, make_address_default, order_detail, payment_completed_view, payment_failed_view, product_detail_view, product_list_view, remove_wishlist, search_view, tag_list, update_cart, vendor_detail_view, vendor_list_view, wishlist_view, contact, about_us, purchase_guide, privacy_policy, terms_of_service, payment_cod_view

app_name = "core"

urlpatterns = [

    path("payment-cod/<oid>/", payment_cod_view, name="payment-cod"),

    # Homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("product/<pid>/", product_detail_view, name="product-detail"),
    path("category/", category_list_view, name="category-list"),
    # path("category/<cid>/", category_product_list__view, name="category-product-list"),
    path("category/<cid>/shop-product-right.html", category_product_list__view, name="category-product-list"),
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),
    path("search/", search_view, name="search"),
    path("filter-products/", filter_product, name="filter-product"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),
    path("update-cart/", update_cart, name="update-cart"),
    path("api/create_checkout_session/<oid>/", create_checkout_session, name="api_checkout_session"),
    path("save_checkout_info/", save_checkout_info, name="save_checkout_info"),
    path("checkout/<oid>/", checkout, name="checkout"),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path("payment-completed/<oid>/", payment_completed_view, name="payment-completed"),
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    path("dashboard/", customer_dashboard, name="dashboard"),
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),
    path("make-default-address/", make_address_default, name="make-default-address"),
    path("wishlist/", wishlist_view, name="wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),
    path("remove-from-wishlist/", remove_wishlist, name="remove-from-wishlist"),
    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),
    path("about_us/", about_us, name="about_us"),
    path("purchase_guide/", purchase_guide, name="purchase_guide"),
    path("privacy_policy/", privacy_policy, name="privacy_policy"),
    path("terms_of_service/", terms_of_service, name="terms_of_service"),
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),
    path("chatbot/", include("chatbot.v2.urls")),
    path("dynamicPrice/", include("products.urls")),
    path('recommendation/', include('recommendation.urls')),


    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

urlpatterns = [
    path('dashboard/', views.pricing_dashboard, name='pricing_dashboard'),
    path('api/update/<int:product_id>/', views.pricing_api_update, name='pricing_api_update'),
    path('api/bulk-update/', views.pricing_api_bulk_update, name='pricing_api_bulk_update'),
    path('api/train-model/', views.train_ml_model, name='train_ml_model'),
]

useradmin/urls.py
from django.urls import path
from useradmin import views

app_name = "useradmin"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("products/", views.products, name="dashboard-products"),
    path("add-products/", views.add_product, name="dashboard-add-products"),
    path("edit-products/<pid>/", views.edit_product, name="dashboard-edit-products"),
    path("delete-products/<pid>/", views.delete_product, name="dashboard-delete-products"),
    path("orders/", views.orders, name="orders"),
    path("order_detail/<id>/", views.order_detail, name="order_detail"),
    path("change_order_status/<oid>/", views.change_order_status, name="change_order_status"),
    path("shop_page/", views.shop_page, name="shop_page"),
    path("reviews/", views.reviews, name="reviews"),
    path("settings/", views.settings, name="settings"),
    path("change_password/", views.change_password, name="change_password"),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

    path("profile/update/", views.profile_update, name="profile-update"),
]

useradmin/models.py
from django.db import models

# Create your models here.

useradmin/forms.py
from core.models import Product
from django import forms
# from bootstrap_datepicker_plus import DatePickerInput



class AddProductForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Product Title", "class":"form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Product Description", "class":"form-control"}))
    price = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "Sale Price", "class":"form-control"}))
    old_price = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "Old Price", "class":"form-control"}))
    type = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Type of product e.g organic cream", "class":"form-control"}))
    stock_count = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "How many are in stock?", "class":"form-control"}))
    life = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "How long would this product live?", "class":"form-control"}))
    mfd = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'placeholder': "e.g: 22-11-02", "class":"form-control"}))
    tags = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Tags", "class":"form-control"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={"class":"form-control"}))

    base_price = forms.DecimalField(widget=forms.NumberInput(attrs={'placeholder': 'Base Price', 'class': 'form-control'}), required=False)
    max_price = forms.DecimalField(widget=forms.NumberInput(attrs={'placeholder': 'Max Price', 'class': 'form-control'}), required=False)
    selling_price = forms.DecimalField(widget=forms.NumberInput(attrs={'placeholder': 'Selling Price', 'class': 'form-control'}), required=False)
    weekly_sales = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder': 'Weekly Sales', 'class': 'form-control'}), required=False)
    last_week_sales = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder': 'Last Week Sales', 'class': 'form-control'}), required=False)
    price_adjustment_step = forms.DecimalField(widget=forms.NumberInput(attrs={'placeholder': 'Price Adjustment Step', 'class': 'form-control'}), required=False)

    class Meta:
        model = Product
        fields = [
            'title',
            'image',
            'description',
            'price',
            'old_price',
            'base_price',
            'max_price',
            'selling_price',
            'weekly_sales',
            'last_week_sales',
            'price_adjustment_step',
            'specifications',
            'type',
            'stock_count',
            'life',
            'mfd',
            'tags',
            'digital',
            'category',
        ]
        widgets = {
            # 'mdf': DateTimePickerInput
        }

useradmin/views.py
from django.shortcuts import render, redirect
from django.db.models import Sum
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.contrib.auth.hashers import check_password


from core.models import CartOrder, CartOrderProducts, Product, Category, ProductReview
from userauths.models import Profile, User
from useradmin.forms import AddProductForm
from useradmin.decorators import admin_required

import datetime



@admin_required
def dashboard(request):
    revenue = CartOrder.objects.aggregate(price=Sum("price"))
    total_orders_count = CartOrder.objects.all()
    all_products = Product.objects.all()
    all_categories = Category.objects.all()
    new_customers = User.objects.all().order_by("-id")[:6]
    latest_orders = CartOrder.objects.all()

    this_month = datetime.datetime.now().month
    monthly_revenue = CartOrder.objects.filter(order_date__month=this_month).aggregate(price=Sum("price"))

    
    context = {
        "monthly_revenue": monthly_revenue,
        "revenue": revenue,
        "all_products": all_products,
        "all_categories": all_categories,
        "new_customers": new_customers,
        "latest_orders": latest_orders,
        "total_orders_count": total_orders_count,
    }
    return render(request, "useradmin/dashboard.html", context)

@admin_required
def products(request):
    all_products = Product.objects.all()
    all_categories = Category.objects.all()
    
    context = {
        "all_products": all_products,
        "all_categories": all_categories,
    }
    return render(request, "useradmin/products.html", context)

@admin_required
def add_product(request):
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            form.save_m2m()
            return redirect("useradmin:dashboard-products")
    else:
        form = AddProductForm()
    context = {
        'form':form
    }
    return render(request, "useradmin/add-products.html", context)

@admin_required
def edit_product(request, pid):
    product = Product.objects.get(pid=pid)

    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.save()
            form.save_m2m()
            return redirect("useradmin:dashboard-products")
    else:
        form = AddProductForm(instance=product)
    context = {
        'form':form,
        'product':product,
    }
    return render(request, "useradmin/edit-products.html", context)

@admin_required
def delete_product(request, pid):
    product = Product.objects.get(pid=pid)
    product.delete()
    return redirect("useradmin:dashboard-products")

@admin_required
def orders(request):
    orders = CartOrder.objects.all()
    context = {
        'orders':orders,
    }
    return render(request, "useradmin/orders.html", context)

@admin_required
def order_detail(request, id):
    order = CartOrder.objects.get(id=id)
    order_items = CartOrderProducts.objects.filter(order=order)
    context = {
        'order':order,
        'order_items':order_items
    }
    return render(request, "useradmin/order_detail.html", context)

@admin_required
@csrf_exempt
def change_order_status(request, oid):
    order = CartOrder.objects.get(oid=oid)
    if request.method == "POST":
        status = request.POST.get("status")
        print("status =======", status)
        messages.success(request, f"Order status changed to {status}")
        order.product_status = status
        order.save()
    
    return redirect("useradmin:order_detail", order.id)

@admin_required
def shop_page(request):
    products = Product.objects.filter(user=request.user)
    revenue = CartOrder.objects.filter(paid_status=True).aggregate(price=Sum("price"))
    total_sales = CartOrderProducts.objects.filter(order__paid_status=True).aggregate(qty=Sum("qty"))

    context = {
        'products':products,
        'revenue':revenue,
        'total_sales':total_sales,
    }
    return render(request, "useradmin/shop_page.html", context)

@admin_required
def reviews(request):
    reviews = ProductReview.objects.all()
    context = {
        'reviews':reviews,
    }
    return render(request, "useradmin/reviews.html", context)

@admin_required
def settings(request):
    profile = Profile.objects.get(user=request.user)

    if request.method == "POST":
        image = request.FILES.get("image")
        full_name = request.POST.get("full_name")
        phone = request.POST.get("phone")
        bio = request.POST.get("bio")
        address = request.POST.get("address")
        country = request.POST.get("country")
        print("image ===========", image)
        
        if image != None:
            profile.image = image
        profile.full_name = full_name
        profile.phone = phone
        profile.bio = bio
        profile.address = address
        profile.country = country

        profile.save()
        messages.success(request, "Profile Updated Successfully")
        return redirect("useradmin:settings")
    
    context = {
        'profile':profile,
    }
    return render(request, "useradmin/settings.html", context)

@admin_required
def change_password(request):
    user = request.user

    if request.method == "POST":
        old_password = request.POST.get("old_password")
        new_password = request.POST.get("new_password")
        confirm_new_password = request.POST.get("confirm_new_password")

        if confirm_new_password != new_password:
            messages.error(request, "Confirm Password and New Password Does Not Match")
            return redirect("useradmin:change_password")
        
        if check_password(old_password, user.password):
            user.set_password(new_password)
            user.save()
            messages.success(request, "Password Changed Successfully")
            return redirect("useradmin:change_password")
        else:
            messages.error(request, "Old password is not correct")
            return redirect("useradmin:change_password")
    
    return render(request, "useradmin/change_password.html")

templates/useradmin/add-products.html
{% extends 'useradmin/base.html' %}
{% load static %}
{% load humanize %}
{{ form.media }}
{% block content %}   
<head>
    <style>
        select {
        appearance: none;
        outline: 0;
        background: rgba(240, 240, 240, 0.548);
        background-image: none;
        width: 100%;
        height: 700px;
        color: black;
        cursor: pointer;
        border: none;
        border-radius: 3px;
    }
     
    #id_category {
        position: relative;
        display: block;
        width: 15em;
        font-family: poppins;
        border: none;
        height: 3em;
        line-height: 3;
        overflow: hidden;
        border-radius: .25em;
        padding-bottom: 10px;
    }
    </style>
</head>
            <section class="content-main">
                <form method="POST" enctype="multipart/form-data">

                <div class="row">
                    <div class="col-9">
                        <div class="content-header">
                            <h2 class="content-title">Add New Product</h2>
                            <div>
                                <button class="btn btn-md rounded font-sm hover-up">Publish <i class="fas fa-check-circle ms-2"></i></button>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-6">
                        <div class="card mb-4">
                            <div class="card-header">
                                <h4>Basic</h4>
                            </div>
                            <div class="card-body">
                                
                                {% if form.errors %}
                                    
                                
                                <div class="alert alert-danger">
                                    <strong>{{ form.errors }}</strong>
                                </div>
                                {% endif %}
                                    {% csrf_token %}
                                    <div class="mb-4">
                                        <label for="product_name" class="form-label">Product title</label>
                                        {{form.title}}
                                        <!-- <input type="text" placeholder="Type here" class="form-control" id="product_name" /> -->
                                    </div>
                                    <div class="mb-4">
                                        <label class="form-label">Full description</label>
                                        {{form.description}}

                                        <!-- <textarea placeholder="Type here" class="form-control" rows="4"></textarea> -->
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-4">
                                            <div class="mb-4">
                                                <label class="form-label">Selling price</label>
                                                <div class="row gx-2">
                                        {{form.price}}

                                                    <!-- <input placeholder="$" type="text" class="form-control" /> -->
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="mb-4">
                                                <label class="form-label">Old price</label>
                                        {{form.old_price}}

                                                <!-- <input placeholder="$" type="text" class="form-control" /> -->
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <label class="form-label">Currency</label>
                                            <select class="form-select">
                                                <option>USD</option>
                                               
                                            </select>
                                        </div>
                                    </div>
                                   <!-- Additional Product Fields -->
                                   <div class="mb-4">
                                       <label class="form-label" for="id_base_price">Base Price</label>
                                       {{ form.base_price }}
                                   </div>
                                   <div class="mb-4">
                                       <label class="form-label" for="id_max_price">Max Price</label>
                                       {{ form.max_price }}
                                   </div>
                                   <div class="mb-4">
                                       <label class="form-label" for="id_selling_price">Selling Price (Calculated)</label>
                                       {{ form.selling_price }}
                                   </div>
                                   <div class="mb-4">
                                       <label class="form-label" for="id_weekly_sales">Weekly Sales</label>
                                       {{ form.weekly_sales }}
                                   </div>
                                   <div class="mb-4">
                                       <label class="form-label" for="id_last_week_sales">Last Week Sales</label>
                                       {{ form.last_week_sales }}
                                   </div>
                                   <div class="mb-4">
                                       <label class="form-label" for="id_price_adjustment_step">Price Adjustment Step</label>
                                       {{ form.price_adjustment_step }}
                                   </div>
                                    <div class="mb-4">
                                        <label class="form-label">Type</label>
                                        {{form.type}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>
                                    <div class="mb-4">
                                        <label class="form-label">Stock</label>
                                        {{form.stock_count}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Life of Product</label>
                                        {{form.life}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Manufactured Date</label>
                                        {{form.mfd}}
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Tags</label>
                                        {{form.tags}}
                                        <small class="text-muted">Seperate tag using comma</small>
                                        <!-- <input type="text" placeholder="%" class="form-control" id="product_name" /> -->
                                    </div>

                                    <div class="mb-4">
                                        <label class="form-label">Digital Product</label>
                                        <br>
                                        {{form.digital}}
                                        <small class="text-muted ms-2">Check if only this is a digital product</small>
                                    </div>
                            </div>
                        </div>
                        <!-- card end// -->
                       
                        <!-- card end// -->
                    </div>
                    <div class="col-lg-3">
                        <div class="card mb-4">
                            <div class="card-header">
                                <h4>Media</h4>
                            </div>
                            <div class="card-body">
                                <div class="input-upload">
                                    <img src="{% static 'assets2/imgs/theme/upload.svg' %}" alt="" />
                                    <!-- <input class="form-control" type="file" /> -->
                                    {{form.image}}
                                </div>
                            </div>
                        </div>
                        <!-- card end// -->
                        <div class="card mb-4">
                            <div class="card-header">
                                <h4>Others</h4>
                            </div>
                            <div class="card-body">
                                <div class="row gx-2">
                                    <div class="col-sm-6 mb-3">
                                        <label class="form-label">Category</label>
                                        {{form.category}}
                                    </div>
                                    
                                </div>
                                <!-- row.// -->
                            </div>
                            <br>
                            
                        </div>
                        <!-- card end// -->
                        <button class="btn mt-3 btn-md rounded font-sm hover-up" type="submit">Create Product</button>
                    </div>
                </div>
                </form>
            </section>
            <!-- content-main end// -->
              
            {% endblock content %}

templates/useradmin/change_password.html
{% extends 'useradmin/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}  

<section class="content-main">
    <div class="content-header">
        <h2 class="content-title">Change Password</h2>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row gx-5">
                <div class="col-lg-12">
                    <section class="content-body p-xl-4">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="row gx-3">
                                        <div class="col-12 mb-3">
                                            <label class="form-label">Old Password</label>
                                            <input class="form-control" name="old_password" value="" type="text" placeholder="***********" />
                                        </div>
                                        <div class="col-12 mb-3">
                                            <label class="form-label">New Password</label>
                                            <input class="form-control" name="new_password" value="" type="text" placeholder="***********" />
                                        </div>
                                        <div class="col-lg-12 mb-3">
                                            <label class="form-label">Confirm Password</label>
                                            <input class="form-control" name="confirm_new_password" value="" type="text" placeholder="***********" />
                                        </div>
                                         
                                    </div>
                                </div>
                                <aside class="col-lg-4">
                                    <figure class="text-lg-center">
                                        
                                        {% if request.user.profile.image %}
                                            <img class="img-lg mb-3 img-avatar" src="{{request.user.profile.image.url}}" alt="User Photo" />
                                        {% else %}
                                            <img class="img-lg mb-3 img-avatar" src="https://www.shutterstock.com/image-vector/vector-flat-illustration-grayscale-avatar-600nw-2281862025.jpg" alt="User Photo" />
                                        {% endif %}
                                    </figure>
                                </aside>
                            </div>
                            <br />
                            <button class="btn btn-primary" type="submit">Save New Password <i class="fas fa-check-circle mt-1 ms-2"></i></button>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}  

templates/useradmin/products.html
{% extends 'useradmin/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Products List</h2>
            <p>Manage all your products from here</p>
        </div>
        <div>
            <a href="{% url 'useradmin:dashboard-add-products' %}" class="btn btn-primary btn-sm rounded">Create Product</a>
        </div>
    </div>
    <div class="card mb-4">
        <header class="card-header">
            <div class="row align-items-center">
                
                <div class="col-md-2 col-6">
                    <select class="form-select">
                        <option selected>Status</option>
                        <option>Active</option>
                        <option>Disabled</option>
                        <option>Show all</option>
                    </select>
                </div>
            </div>
        </header>
        <div class="card-body">
            {% for p in all_products %}
            <article class="itemlist">
                <div class="row align-items-center">
                    <div class="col-lg-4 col-sm-4 col-8 flex-grow-1 col-name">
                        <a class="itemside" href="{% url 'core:product-detail' p.pid %}">
                            <div class="left">
                                <img src="{{p.image.url}}" style="width: 100px; height: 100px; object-fit: cover; border-radius: 15px;" class="img-sm img-thumbnail" alt="Item" />
                            </div>
                            <div class="info">
                                <h6 class="mb-0">{{p.title}}</h6>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-2 col-sm-2 col-4 col-price"><span>${{p.price}}</span></div>
                    <div class="col-lg-2 col-sm-2 col-4 col-status"><span class="badge  alert-dark">{{p.product_status|title}}</span></div>
                    <div class="col-lg-1 col-sm-2 col-4 col-date"><span>{{p.date}}</span></div>
                    <div class="col-lg-2 col-sm-2 col-4 col-action text-end">
                        <a href="{% url 'useradmin:dashboard-edit-products'  p.pid %}" class="btn btn-sm font-sm rounded btn-brand"> <i class="material-icons md-edit"></i> Edit </a>
                        <a href="{% url 'useradmin:dashboard-delete-products' p.pid  %}" class="btn btn-sm font-sm btn-light rounded"> <i class="material-icons md-delete_forever"></i> Delete </a>
                    </div>
                </div>
            </article>
            {% endfor %}
        </div>
    </div>
    
</section>

{% endblock content %}